platform :ios, '13.0'

target 'zip_official' do
  use_frameworks!

pod 'GooglePlaces', '4.2.0'


pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'

#UIKit
pod 'MARKRangeSlider'
pod 'MessageKit'
pod 'DropDown'
pod 'MTSlideToOpen'
pod 'RSKImageCropper'

#FireBase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'Firebase/Crashlytics'


end
