platform :ios, '13.0'

target 'zip_official' do
  use_frameworks!

pod 'GooglePlaces', '6.0.0'


pod 'JGProgressHUD'
pod 'SDWebImage'


#UIKit
pod 'MARKRangeSlider'
pod 'MessageKit'
pod 'DropDown'
pod 'MTSlideToOpen'
pod 'PMAlertController' 
pod 'FloatingPanel'
pod 'RSKImageCropper'
pod 'UIImageCropper'

#FireBase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'Firebase/Crashlytics'


pod 'GeoFire', '~> 4.0'
pod 'mailcore2-ios'


end
